### ISSUE TITLE
Arrows are shifted down

### ISSUE THREAD

**Issue by wooloba** [sonoisa/XyJax#14]
Hello,
I am using XyJax in my React project.
I have imported/configured MathJax(2.7.1) and XyJax in my project, but when comes to rendering it seems all arrows and other graphs are all shifted down a lot.
For example, the following:
![image](https://user-images.githubusercontent.com/15993216/62740491-435ff900-b9f5-11e9-8f17-1cbaeab35021.png)
I think there is something wrong with the CSS.
Is it because I am using a newer version of MathJax or there is something wrong with my code?

Thank you.

**Comment by alexjbest** [comment]
I also had this issue once. Did you work out what caused it precisely?

**Comment by wooloba** [comment]
Yes. This issue is most likely caused by CSS confliction.
In my case, I used React-Bootstrap library. And their CSS conflicts with XyJax. If you are using React-Bootstrap as well, the line causes the confliction is `vertical-align: middle` in `svg{ }`. Everything works fine if you could comment this line out no matter how.
